CREATE DATABASE IF NOT EXISTS sudere;

USE sudere;

CREATE TABLE lines(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(80) NOT NULL);

CREATE TABLE series(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(80) NOT NULL);

CREATE TABLE users(
id VARCHAR(8) NOT NULL PRIMARY KEY ,
firstname VARCHAR(80) NOT NULL,
lastname VARCHAR(200) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
center VARCHAR(80) NOT NULL,
access VARCHAR(80) NOT NULL);

CREATE TABLE trains(
id INT NOT NULL PRIMARY KEY,
id_line FOREIGN KEY REFERENCES lines(id),
id_serie FOREIGN KEY REFERENCES series(id));

CREATE TABLE trailers(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
number INT NOT NULL,
date DATE,
`processing-time` INT,
id_train FOREIGN KEY REFERENCES trains(id),
id_user FOREIGN KEY REFERENCES users(id));
